
services:
  mongo:
    image: mongo:4.0-xenial
    hostname: mongo
    command: ["--replSet", "hehe", "--bind_ip_all"]
    ports:
      - 37017:37017
    networks:
      - shake
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_SET_NAME: hehe
      MONGO_INITDB_DATABASE: initdb
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
        
  mongoshake:
    image: hongmin/mongoshake
    hostname: mongoshake
    ports:
      - 9101:9101
      - 9100:9100
      - 9102:9102
      - 30000:30000
    volumes:
      - type: bind
        source: ./conf/collector-impl.conf
        target: /go/conf/collector.conf
    networks:
      - shake
      
networks:
  shake:
      
